backend:
  name: github
  repo: WithdewHua/withdewhua-hugo
  branch: master
  accept_roles: #optional - accepts all users if left out
   - admin
   - editor

publish_mode: editorial_workflow

media_folder: static/img/post
public_folder: /img/post

display_url: https://withdewhua.space/
# logo_url: https://cdn.jsdelivr.net/gh/WithdewHua/chaos-cdn/withdewhua-hugo/img/favicon/favicon-32x32.png

collections:
  - name: "post"
    label: "Blog"
    folder: "content/blog/2018"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "WithdewHua",
        }
      - { label: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Series", name: "series", widget: "list", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Lastmod",
          name: "lastmod",
          widget: "date",
          default: "",
          required: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Alt",
          name: "featuredalt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Path",
          name: "featuredpath",
          widget: "string",
          default: "img/post",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Show TOC",
          name: "showtoc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Post Content", name: "body", widget: "markdown" }
